name: Generate Friend Links Data

on:
  # Run when the workflow is triggered manually.
  workflow_dispatch:
  # Run when a modification is made to the issues.
  issues:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup rust-script
      run: cargo install rust-script
    - name: Run src/script.ers
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        chmod +x src/script.ers
        ./src/script.ers
    - name: Upload generated data as artifact
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: |
          ./output/linksData.js
          ./output/linksData.json
    - name: Delete existing data branch
      uses: dawidd6/action-delete-branch@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branches: data
        soft_fail: true
    - name: Upload generated data to data branch
      uses: LarchLiu/actions-save-files@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: data
        publish_dir: output
        destination_dir: .
